### ISSUE TITLE
Output of `e3sm.py` is not printed

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#13]
Currently, if `python e3sm.py` fails, the error may not be printed to the `e3sm_diags_*.o*` log file. However, if `python e3sm.py` is run from the terminal, the full error stack trace will print. We therefore have to get all otuput of `python e3sm.py` to print in the log file

**Comment by forsyth2** [comment]
Steps to reproduce:
- Cause an error in an `e3sm_diags` bash file (e.g., by commenting out `qbo_param.ref_start_yr = ref_start_yr ` in `e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0001-0020.bash` with the changes in #2. It will save time if you also set it to just run `qbo`: `runner.sets_to_run = ['qbo'] `. Also set `debug=True`.).
- Run that file (e.g., `sbatch e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0001-0020.bash`)
- Notice the line `There was not a single valid diagnostics run, no viewer created.` in the output file (e.g., `e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0001-0020.o<job-id>`). You will not however know the error.
- If you `cd` into the `tmp` directory created, you can run `python e3sm.py`. That output gives much more information:
```
There was not a single valid diagnostics run, no viewer created.
Error in acme_diags.driver.qbo_driver
Traceback (most recent call last):
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/driver/qbo_driver.py", line 159, in run_diag
    parameter.ref_yrs = utils.general.get_yrs(ref_data)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/driver/utils/general.py", line 94, in get_yrs
    start_yr, end_yr = dataset.get_start_and_end_years()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/driver/utils/dataset.py", line 225, in get_start_and_end_years
    start_yr = getattr(self.parameters, 'ref_start_yr')
AttributeError: 'QboParameter' object has no attribute 'ref_start_yr'
```

**Comment by forsyth2** [comment]
The relevant code block is:
```
# Handle cases when cfg file is explicitly provided                                                                                                     

command="python e3sm.py"


# Run diagnostics                                                                                                                                       
time ${command}
if [ $? != 0 ]; then
  cd ..
  echo 'ERROR (1)' > e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0001-0020.status
  exit 1
fi
```
For some reason, running the command inside the batch script leaves out the stack trace.
