### ISSUE TITLE
Nested `srun` calls in MPAS-Analysis don't work on Cori

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#170]
On cori-haswell or cori-knl, if `mpas_analysis` gets called with `srun`:
https://github.com/E3SM-Project/zppy/blob/3f500387a887c82ee88b3a1e0e9f96349ff70c82/zppy/templates/mpas_analysis.bash#L311
and then tries to call something internally with `srun`, we see:
```
running: srun -n 6 /global/common/software/e3sm/anaconda_envs/system/cori-haswell/e3sm_unified_1.5.0/intel/mpt/esmf_8.1.1/bin/ESMF_RegridWeightGen --source /global/cscratch1/sd/xylar/test_noel_high_res4/clim/clim/analysis/mpas_analysis/ts_0056-0057_climo_0056-0057/mapping/tmpskiqolk7/src_mesh.nc --destination /global/cscratch1/sd/xylar/test_noel_high_res4/clim/clim/analysis/mpas_analysis/ts_0056-0057_climo_0056-0057/mapping/tmpskiqolk7/dst_mesh.nc --weight /global/cscratch1/sd/xylar/test_noel_high_res4/clim/clim/analysis/mpas_analysis/ts_0056-0057_climo_0056-0057/mapping/map_oRRS18to6v3_to_WOCE_transects_5km_bilinear.nc --method bilinear --netcdf4 --no_log --src_loc center --src_regional --dst_regional --ignore_unmapped
srun: Job 51412223 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Job 51412223 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 51412223 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 51412223 step creation still disabled, retrying (Requested nodes are busy)
...
```
and the job never completes.

The solution is to not call `mpas_analysis` with `srun` at all, at least on Cori.  I'll make a PR to fix this before the next release.

**Comment by milenaveneziani** [comment]
@xylar, I am not sure why, but I think I got these error messages also with mpas-analysis standalone on cori. I went back to a previous hash (fbb1f518) and I didn't get those errors anymore.
I was running `python -m mpas_analysis --verbose $configFile`.
I can re-checkout the latest develop and re-run and report back.

**Comment by milenaveneziani** [comment]
Here is the error I get:
```
Detected E3SM supported machine: cori-haswell
Using the following config files:
   /global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/default.cfg
   /global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/lib/python3.8/site-packages/mache/machines/cori-haswell.cfg
   /global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/configuration/cori-haswell.cfg
   config.20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart
copying /global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/config.20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart to HTML dir.

running: srun -n 12 /global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/bin/ESMF_RegridWeightGen --source /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpt9zf_t7p/src_mesh.nc --destination /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpt9zf_t7p/dst_mesh.nc --weight /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/map_ARRM60to10_to_0.5x0.5degree_bilinear.nc --method bilinear --netcdf4 --no_log --src_loc center --src_regional --ignore_unmapped
srun: error: No architecture specified, cannot estimate job costs.
srun: error: Unable to allocate resources: Unspecified error
Traceback (most recent call last):
  File "/global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/__main__.py", line 383, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py", line 213, in setup_and_check
    self._setup_remappers()
  File "/global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py", line 422, in _setup_remappers
    self.remappers[comparisonGridName] = get_remapper(
  File "/global/project/projectdirs/e3sm/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 133, in get_remapper
    remapper.build_mapping_file(method=method, logger=logger,
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/lib/python3.8/site-packages/pyremap/remapper.py", line 303, in build_mapping_file
    subprocess.check_call(args, stdout=DEVNULL)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['srun', '-n', '12', '/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/bin/ESMF_RegridWeightGen', '--source', '/global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpt9zf_t7p/src_mesh.nc', '--destination', '/global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpt9zf_t7p/dst_mesh.nc', '--weight', '/global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/map_ARRM60to10_to_0.5x0.5degree_bilinear.nc', '--method', 'bilinear', '--netcdf4', '--no_log', '--src_loc', 'center', '--src_regional', '--ignore_unmapped']' returned non-zero exit status 1.
Warning: climatologyMapMLD: remapMpasClimatology failed during check and will not be run
Warning: subtask of climatologyMapMLD failed during check, so this task will not be run
running: srun -n 12 /global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_nompi/bin/ESMF_RegridWeightGen --source /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpe4x6lmfu/src_mesh.nc --destination /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/tmpe4x6lmfu/dst_mesh.nc --weight /global/project/projectdirs/m1199/milena/analysis/mpas/20211129.WCYCL1950.ne30pg2_oARRM60to10.amoc-branch-coldStart/mapping/map_ARRM60to10_to_0.5x0.5degree_bilinear.nc --method bilinear --netcdf4 --no_log --src_loc center --src_regional --ignore_unmapped
srun: error: No architecture specified, cannot estimate job costs.
srun: error: Unable to allocate resources: Unspecified error
...
```

which seems similar to the one you report here.

**Comment by xylar** [comment]
@milenaveneziani, thanks for letting me know.

At this point, it's preferable to do:
```
conda create -y -n mpas_dev --file dev-spec.txt
conda activate mpas_dev
python -m pip install -e .
```
If you do that, there's no need to do `python -m mpas_analysis ...`.  You can just to `mpas_analysis ...`.

But that's likely unrelated to seeing the issue or not.  The important questions for what you saw are:
1. Are you certain you weren't running `mpas_analysis` with `srun`?  If so, I haven't ever seen this behavior under those circumstances before and that would be important (but unfortunate) news.
2. Were you running on a login or a compute node?
3. Were you running on Haswell or KNL?

**Comment by xylar** [comment]
Ah, seeing your message now.  That's unrelated to this issue.  That's because you're running on a login node, I believe.  You can do that but you'll need to set:
```
[execute]
## options related to executing parallel tasks

# the number of MPI tasks to use in creating mapping files (1 means tasks run in
# serial, the default)
mapMpiTasks = 1

# "None" if ESMF should perform mapping file generation in serial without a
# command, or one of "srun" or "mpirun" if it should be run in parallel (or ins
# serial but with a command)
mapParallelExec = None

# "None" if ncremap should perform remapping without a command, or "srun"
# possibly with some flags if it should be run with that command
ncremapParallelExec = None
```
The default assumes you're on a compute node.  (Which you should be!)

**Comment by milenaveneziani** [comment]
Indeed, I am lazy (but only when I know that the analysis is not heavy! ;))
Anyways, thanks for clarifying.
