### ISSUE TITLE
Unhelpful generic `Exception`

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#175]
I tried to run analysis in which I had forgotten the following in my config file:
``` cfg
[e3sm_diags_vs_model]
active = False

```
The resulting output was a generic `Exception` that wasn't very helpful:
```
$ zppy -c high_res.cfg 
Configuration file validation passed
Error interpreting years 
Traceback (most recent call last):
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/__main__.py", line 103, in main
    e3sm_diags_vs_model(config, scriptDir)
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/e3sm_diags_vs_model.py", line 28, in e3sm_diags_vs_model
    year_sets = getYears(c["years"])
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/utils.py", line 98, in getYears
    raise Exception
Exception
```

My understanding is that there are pretty much never circumstances where it is useful to raise a generic `Exception` without an error message.  In this particular case, I would have expected to get a `ValueError` and a message telling me that the `years` config option is required in the `e3sm_diags_vs_model` section.

**Comment by xylar** [comment]
After fixing that error, I got another generic `Exception`:
```
b'sbatch: error: No architecture specified, cannot estimate job costs.\nsbatch: error: Batch job submission failed: Unspecified error\n'
Traceback (most recent call last):
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/__main__.py", line 109, in main
    mpas_analysis(config, scriptDir)
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/mpas_analysis.py", line 100, in mpas_analysis
    jobid = submitScript(scriptFile, dependFiles=dependencies)
  File "/global/homes/x/xylar/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/utils.py", line 172, in submitScript
    raise Exception
Exception
```
There is an error message before the `Exception`, but this is not what I (and I think experienced python users in general) would expect.
