### ISSUE TITLE
Fix test_campaign_high_res_v1 error

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#183]
Fix `test_campaign_high_res_v1` error. Presumably this is because there is no `[tc_analysis]` section in the `cfg` file (the last time #179 was tested must have been before #169 merged). Note that is the same unhelpful error reported in #175.

```
$ zppy -c tests/integration/test_campaign_high_res_v1.cfg
Configuration file validation passed
Error interpreting years 
Traceback (most recent call last):
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev_v200rc1/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev_v200rc1/lib/python3.7/site-packages/zppy/__main__.py", line 101, in main
    tc_analysis(config, scriptDir)
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev_v200rc1/lib/python3.7/site-packages/zppy/tc_analysis.py", line 34, in tc_analysis
    year_sets = getYears(c["years"])
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev_v200rc1/lib/python3.7/site-packages/zppy/utils.py", line 98, in getYears
    raise Exception
Exception
```

**Comment by forsyth2** [comment]
This error also occurs in `test_campaign_cryosphere_override` and `test_campaign_water_cycle_override`

**Comment by golaz** [comment]
@forsyth2 : this is annoying about missing sections. Every single section needs to be listed in the cfg file. I really wish there was a work around, so that missing sections are simply turned off. But I haven't found one (did not spend a whole lot of time either).

**Comment by forsyth2** [comment]
@golaz Can we make `active=False` the default, rather than `active=True`? That will make it easy to omit unneeded sections. I suppose that would be an incompatible API change (since users would have to start specifying `active=True`, but we're incrementing the major version for this release anyway.

**Comment by golaz** [comment]
@forsyth2 : sure, you can make that change. I thought something else was causing trouble, but I don't remember the details.

**Comment by xylar** [comment]
I really support `active=False` being the default.
