### ISSUE TITLE
Validator does not provide useful feedback

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#47]
When a configuration file fails the validation phase, we only get a very obscure error:

```
Traceback (most recent call last):
  File "/global/cfs/cdirs/e3sm/golaz/conda/envs/zppy_dev/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/global/cfs/cdirs/e3sm/golaz/conda/envs/zppy_dev/lib/python3.7/site-packages/zppy/__main__.py", line 33, in main
    raise Exception('Configuration file validation failed')
Exception: Configuration file validation failed
```

Either we need a more explicit message, or we should consider disabling the validator for now.

**Comment by forsyth2** [comment]
In #2, we started printing validation results (https://github.com/E3SM-Project/zppy/pull/2/files#diff-f8d678186320c387497cd7685c0f00d5d4668b42f0a1a75f74e25a1473473eddR30)

For example:
```
Validation results={'default': {'input': False, 'input_subdir': True, 'output': True, 'case': True, 'www': False, 'debug': True, 'partition': True, 'e3sm_unified': True, 'dry_run': True}, 'climo': True, 'ts': True, 'e3sm_diags': True, 'e3sm_diags_vs_model': True, 'amwg': True, 'mpas_analysis': True, 'global_time_series': True}
Traceback (most recent call last):
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/home/ac.forsyth2/miniconda3/envs/zppy_dev/lib/python3.7/site-packages/zppy/__main__.py", line 33, in main
    raise Exception('Configuration file validation failed')
Exception: Configuration file validation failed
```
`'input'` and `'www'` are `False`, so those are the parameters causing validation failures. Is that sufficient or do you want more explanation to be shown?

**Comment by forsyth2** [comment]
Closing in favor of #281.
