### ISSUE TITLE
Unified rc12 testing: KeyError on Perlmutter

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#481]
```
$ zppy -c tests/integration/generated/test_complete_run_pm-cpu.cfg
$ cd /global/cfs/cdirs/e3sm/forsyth/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts
$ tail mpas_analysis_ts_1850-1854_climo_1850-1854.o13973662 
ERROR in task climatologyMapSeaIceProductionSH: plotJJA_antarctic_extended.  See log file /global/cfs/cdirs/e3sm/forsyth/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts/../analysis/mpas_analysis/ts_1850-1854_climo_1850-1854/logs/climatologyMapSeaIceProductionSH_plotJJA_antarctic_extended.log for details
Running tasks:  97% |########################################  | ETA:   0:00:03
Running tasks:  97% |######################################### | ETA:   0:00:03
Running tasks:  98% |######################################### | ETA:   0:00:01
Running tasks:  99% |######################################### | ETA:   0:00:01
Running tasks:  99% |######################################### | ETA:   0:00:00
Running tasks: 100% |##########################################| ETA:  00:00:00
Running tasks: 100% |##########################################| Time:  0:02:18

There were errors in task climatologyMapSeaIceProductionSH: plotJJA_antarctic_extended
$ cat /global/cfs/cdirs/e3sm/forsyth/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts/../analysis/mpas_analysis/ts_1850-1854_climo_1850-1854/logs/climatologyMapSeaIceProductionSH_plotJJA_antarctic_extended.log

Plotting 2-d maps of Sea Ice Production climatologies for JJA on the antarctic_extended grid...
analysis task climatologyMapSeaIceProductionSH_plotJJA_antarctic_extended failed during run 
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/xarray/core/dataset.py", line 1382, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'validMask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/mpas_analysis/shared/analysis_task.py", line 322, in run
    self.run_task()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/mpas_analysis/shared/plot/plot_climatology_map_subtask.py", line 479, in run_task
    self._plot_projection(remappedModelClimatology,
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/mpas_analysis/shared/plot/plot_climatology_map_subtask.py", line 573, in _plot_projection
    validMask = remappedModelClimatology['validMask'].values
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/xarray/core/dataset.py", line 1473, in __getitem__
    return self._construct_dataarray(key)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/xarray/core/dataset.py", line 1384, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0rc12_pm-cpu/lib/python3.10/site-packages/xarray/core/dataset.py", line 196, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'validMask'

Execution time: 0:00:00.22
```

**Comment by forsyth2** [comment]
> can you open up permissions

I ran `chmod -R o+r zppy_test_complete_run_output`, so you should be able to look now. I renamed the `post` directory, so it's `/global/cfs/cdirs/e3sm/forsyth/zppy_test_complete_run_output/v2.LR.historical_0201/post_20230815`.

> Can you rerun in a new output directory to make sure the issue is reproducible?

I'm running a smaller version of the original `cfg` now just to test MPAS-Analysis:
```
[default]
case = v2.LR.historical_0201
constraint = "cpu"
dry_run = "False"
environment_commands = "source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.9.0rc12_pm-cpu.sh"
input = "/global/cfs/cdirs/e3sm/forsyth//E3SMv2/v2.LR.historical_0201"
input_subdir = archive/atm/hist
mapping_file = "map_ne30pg2_to_cmip6_180x360_aave.20200201.nc"
# To run this test, edit `output` and `www` in this file, along with `actual_images_dir` in test_complete_run.py              
output = "/global/cfs/cdirs/e3sm/forsyth/zppy_test_pm/v2.LR.historical_0201"
partition = ""
qos = "regular"
www = "/global/cfs/cdirs/e3sm/www/forsyth/zppy_test_pm_www"

[mpas_analysis]
active = True
anomalyRefYear = 1850
climo_years ="1850-1854", "1855-1860",
enso_years = "1850-1854", "1855-1860",
mesh = "EC30to60E2r2"
parallelTaskCount = 6
partition = ""
qos = "regular"
ts_years = "1850-1854", "1850-1860",
walltime = "01:00:00"
```

**Comment by xylar** [comment]
Yes, I think it happened to be in the middle of output when the run failed.  I would recommend always running in an empty output directory for testing purposes, rather than trying to rerun an existing test.

**Comment by forsyth2** [comment]
> I would recommend always running in an empty output directory for testing purposes, rather than trying to rerun an existing test.

I'll keep that in mind for future runs, thanks.

It's a little frustrating, since one of the benefits of `zppy` is simply re-running `zppy -c my_parameters.cfg` (e.g., using the same `output` directory) to rerun failed tasks. That said, that problem isn't specific to MPAS-Analysis; I'm pretty sure I've encountered a similar issue with `global_time_series`. And yes certainly for testing, a fresh directory is a good idea.
